PACKAGE_NAME="hidpp-g733"
PACKAGE_VERSION="1.0"
PRE_BUILD="prep.sh ${kernelver}"
MAKE[0]="make KVER=${kernelver}"
CLEAN="true"
BUILT_MODULE_NAME[0]="hid-logitech-hidpp"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
